name: Testing unify

on: push

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run black check
      run: poetry run black --check .

  unittests:
    runs-on: ubuntu-latest
    environment: unify-testing
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev
    - name: Download cache
      uses: actions/download-artifact@v4
      with:
        name: cache
        path: .cache.json
    - name: Run unit tests
      run: poetry run pytest -p no:warnings -vv --cov="unify" -n 4 .
      env:
        UNIFY_KEY: ${{ secrets.USER_API_KEY }}
    - name: Upload cache
      uses: actions/upload-artifact@v4
      with:
        name: cache
        path: .cache.json
        if-no-files-found: error
        overwrite: true
        include-hidden-files: true
